version: '3.4'

services:
  
  discountdb:
    image: postgres

  catalogdb:
    image: mongo
  
  basketdb:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  pgadmin:
    image: dpage/pgadmin4

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog.api:
    image: marophius/ifshopping-catalog.api
    # build:
    #   context: .
    #   dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: marophius/ifshopping-basket.api
    # build:
    #   context: .
    #   dockerfile: src/Services/Basket/Basket.Api/Dockerfile

  discount.grpc:
    image: marophius/ifshopping-discount.grpc
    # build:
    #   context: .
    #   dockerfile: src/Services/Discount/Discount.GRPC/Dockerfile

  ordering.api:
    image: marophius/ifshopping-ordering.api
    # build:
    #   context: .
    #   dockerfile: src/Services/Ordering/Orderin.API/Dockerfile



  ocelot.apigateway:
    image: marophius/ifshopping-ocelot.apigateway
    # build:
    #   context: .
    #   dockerfile: src/ApiGateways/Ocelot.ApiGateway/Dockerfile

  # ifshopping.identity:
  #   image: ${DOCKER_REGISTRY-}ifshoppingidentity
  #   build:
  #     context: .
  #     dockerfile: src/Infrastructure/IFShopping.Identity/Dockerfile

  # yarp.apigateway:
  #   image: ${DOCKER_REGISTRY-}yarpapigateway
  #   build:
  #     context: .
  #     dockerfile: src/ApiGateways/Yarp.ApiGateway/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  elasticsearch-data:






