version: '3.4'

services:

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
       - mongo_data:/data/db  

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings:DatabaseName=CatalogDb"
      - "DatabaseSettings:CollectionName=Products"
      - "DatabaseSettings:BrandsCollection=Brands"
      - "DatabaseSettings:TypesCollection=Types"
    depends_on:
      - catalogdb
    ports:
      - "9000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - CacheSettings:ConnectionString=basketdb:6379
    depends_on:
      - basketdb
    ports:
      - "9001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
