version: '3.4'

services:

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eShopping.net
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
       - mongo_data:/data/db  

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings:DatabaseName=CatalogDb"
      - "DatabaseSettings:CollectionName=Products"
      - "DatabaseSettings:BrandsCollection=Brands"
      - "DatabaseSettings:TypesCollection=Types"
    depends_on:
      - catalogdb
    ports:
      - "9000:8080"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - CacheSettings:ConnectionString=basketdb:6379
    depends_on:
      - basketdb
    ports:
      - "9001:8080"


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    ports:
      - "9002:8080"
    depends_on: 
      - discountdb
